name: Release

on:
  push:
    tags:
      - "*"

jobs:
  process:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      USER: zispace
      SRC_REPO: scripts
      SRC_DIR: src
      OUT_DIR: release

    steps:
      - uses: actions/checkout@v4

      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.SRC_REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ${{ env.SRC_DIR }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run scripts
        # if: github.event.schedule == ''
        run: |
          bash ${{ env.SRC_DIR }}/run-export-chars.sh \
            ${{ env.SRC_DIR }} ${{ env.OUT_DIR }} \
            data-charlist,data-charset

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.OUT_DIR }}/*.zip

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.OUT_DIR }}/*.zip
